### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ben-ihelputech** [yafethtb/Geekbench-Web-Scraping-Project#1]
What's the license for this project? No license assumes all rights are reserved.

**Comment by yafethtb** [comment]
Hi. Thanks for reminding me. I haven't consider to put license on this project when I posted this. For now let's consider it no license for now, at least until I found what proper license I can for this project.

**Comment by yafethtb** [comment]
I just put MIT License for this project. Thanks for the question.
